services:
  app:
    build:
      context: .
      dockerfile: ./docker/python/Dockerfile
      target: runner
    platform: linux/amd64
    image: its-you-runner
    container_name: its-you-app
    tty: true
